version: '3.7'
services:
  postgres:
    container_name: postgres
    image: postgres:15
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - ./data/postgresql/data/:/var/lib/postgresql/data

  django:
    container_name: django
    command: bash -c "poetry run python manage.py migrate &&
      poetry run python manage.py setup &&
      poetry run python manage.py init_chans &&
      poetry run python manage.py runserver 0.0.0.0:8000"
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis
    depends_on:
      - postgres
    image: django