# Generated by Django 4.2.3 on 2023-07-03 18:52

import common.utils
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=common.utils.generate_filename)),
                ('caption', models.CharField(blank=True, max_length=50)),
                ('author', models.CharField(blank=True, default='Unknown', max_length=50)),
                ('hash', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Chan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CharacterName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserChanImageAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('mode', models.CharField(choices=[('easy', 'Easy'), ('normal', 'Normal'), ('hard', 'Hard')], default='normal', max_length=6)),
                ('is_solved', models.BooleanField(default=False)),
                ('is_pending', models.BooleanField(default=True)),
                ('is_shown', models.BooleanField(default=False)),
                ('given_answer', models.CharField(default='', max_length=32)),
                ('guess_hints', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='ChanImage',
            fields=[
                ('baseimage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='game.baseimage')),
            ],
            bases=('game.baseimage',),
        ),
        migrations.CreateModel(
            name='CharacterImage',
            fields=[
                ('baseimage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='game.baseimage')),
            ],
            bases=('game.baseimage',),
        ),
    ]
