# Generated by Django 4.1.1 on 2022-09-16 19:01

from django.db import migrations, models
import django.db.models.deletion
import game.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChanImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=50)),
                ('author', models.CharField(default='Unknown', max_length=50)),
                ('image', models.ImageField(upload_to=game.models.generate_filename)),
                ('hash', models.CharField(blank=True, max_length=20, unique=True)),
                ('chan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.chan')),
            ],
        ),
    ]
