# Generated by Django 4.1.1 on 2022-09-16 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chanimage',
            name='name',
        ),
        migrations.AddField(
            model_name='chanimage',
            name='caption',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
    ]
