# Generated by Django 4.2.3 on 2023-07-03 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchanimageattempt',
            name='answer_lang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.lang'),
        ),
        migrations.AddField(
            model_name='userchanimageattempt',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='charactername',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.character'),
        ),
        migrations.AddField(
            model_name='charactername',
            name='lang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.lang'),
        ),
        migrations.AddField(
            model_name='chan',
            name='character',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chan', to='game.character'),
        ),
        migrations.AddField(
            model_name='userchanimageattempt',
            name='chan_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.chanimage'),
        ),
        migrations.AddField(
            model_name='characterimage',
            name='character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.character'),
        ),
        migrations.AddField(
            model_name='chanimage',
            name='chan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.chan'),
        ),
    ]
