# Generated by Django 4.1.1 on 2022-09-16 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_lang'),
        ('game', '0002_alter_chanimage_chan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chanimage',
            name='author',
            field=models.CharField(blank=True, default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='chanimage',
            name='caption',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='ChanAlternative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('chan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.chan')),
                ('lang', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.lang')),
            ],
        ),
    ]
