# Generated by Django 4.1.1 on 2022-09-16 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_remove_chanimage_name_chanimage_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='chanimage',
            name='author',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AlterField(
            model_name='chanimage',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
