# Generated by Django 4.2.3 on 2023-07-12 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chan',
            name='name',
        ),
        migrations.AlterField(
            model_name='chan',
            name='character',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chan', to='game.character'),
        ),
        migrations.AlterField(
            model_name='chanimage',
            name='chan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.chan'),
        ),
    ]
