# Generated by Django 4.1.1 on 2022-09-17 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_character_characterimage_charactername_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='characterimage',
            old_name='chan',
            new_name='character',
        ),
    ]
