# Generated by Django 4.2.3 on 2023-07-12 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_remove_chan_name_alter_chan_character_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactername',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='charactername',
            unique_together={('character', 'name')},
        ),
    ]
