# Generated by Django 4.1.1 on 2022-10-05 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_userchanbatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchanbatch',
            name='mode',
            field=models.CharField(choices=[('easy', 'Easy'), ('normal', 'Normal'), ('hard', 'Hard')], default='normal', max_length=6),
        ),
    ]
