# Generated by Django 4.1.1 on 2022-10-05 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_userchanbatch_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchanbatch',
            name='is_solved',
            field=models.BooleanField(default=False),
        ),
    ]
