# Generated by Django 4.1.1 on 2022-12-04 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_userchanattempt_delete_userchanbatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchanattempt',
            name='chan_image',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='game.chanimage'),
            preserve_default=False,
        ),
    ]
