# Generated by Django 4.1.1 on 2022-12-04 22:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0010_userchanattempt_chan_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserChanAttempt',
            new_name='UserChanImageAttempt',
        ),
    ]
