# Generated by Django 4.1.1 on 2022-12-04 23:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0011_rename_userchanattempt_userchanimageattempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchanimageattempt',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 4, 23, 48, 11, 210980, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userchanimageattempt',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
