# Generated by Django 4.1.1 on 2022-12-04 23:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_alter_userchanimageattempt_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchanimageattempt',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
