# Generated by Django 4.1.1 on 2023-04-18 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_alter_userchanimageattempt_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchanimageattempt',
            name='is_shown',
            field=models.BooleanField(default=False),
        ),
    ]
