# Generated by Django 4.1.1 on 2023-06-21 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_userchanimageattempt_is_shown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chan',
            name='character',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chan', to='game.character'),
        ),
    ]
