# Generated by Django 4.1.1 on 2023-06-26 18:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0017_alter_chan_character'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchanimageattempt',
            name='given_answer',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='userchanimageattempt',
            name='shown_letters',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1), default=list, size=None),
        ),
    ]
