# Generated by Django 4.1.1 on 2023-06-26 19:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0018_userchanimageattempt_given_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchanimageattempt',
            name='words_lengths',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
    ]
