# Generated by Django 4.1.1 on 2023-06-27 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0019_userchanimageattempt_words_lengths'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userchanimageattempt',
            name='shown_letters',
        ),
        migrations.RemoveField(
            model_name='userchanimageattempt',
            name='words_lengths',
        ),
        migrations.AddField(
            model_name='userchanimageattempt',
            name='guess_hints',
            field=models.JSONField(default=None),
            preserve_default=False,
        ),
    ]
