# Generated by Django 4.1.1 on 2023-06-28 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0021_userchanimageattempt_answer_lang'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userchanimageattempt',
            name='chan',
        ),
    ]
