# Generated by Django 4.1.1 on 2023-07-03 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0022_remove_userchanimageattempt_chan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseimage',
            name='hash',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
