# Generated by Django 4.2.3 on 2023-07-04 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_always_show_correct_answer',
            field=models.BooleanField(default=False),
        ),
    ]
