# Generated by Django 4.1.1 on 2022-09-16 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alpha', models.CharField(max_length=5, unique=True)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
    ]
