# Generated by Django 4.1.1 on 2022-09-20 17:25

import common.utils
from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_user_is_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[500, 500], upload_to=common.utils.generate_filename),
        ),
    ]
