# Generated by Django 4.1.1 on 2022-09-20 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_confirmed',
        ),
    ]
