# Generated by Django 4.1.1 on 2022-12-04 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_remove_user_is_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='energy',
            field=models.IntegerField(default=0),
        ),
    ]
