# Generated by Django 4.1.1 on 2022-12-04 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_user_energy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='energy',
            field=models.IntegerField(default=10),
        ),
    ]
