# Generated by Django 4.1.1 on 2023-06-21 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_alter_user_energy'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lang',
            field=models.CharField(default='en', max_length=2, verbose_name='Language'),
        ),
    ]
