# Generated by Django 4.1.1 on 2023-06-21 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_user_lang'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lang',
            old_name='alpha',
            new_name='alpha2',
        ),
    ]
