# Generated by Django 4.1.1 on 2023-06-27 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_alter_user_lang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='lang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.lang'),
        ),
    ]
